### ISSUE TITLE
关于论文中的生成细节

### ISSUE THREAD

**Issue by tcqiuyu** [wdimmy/Automatic-Corpus-Generation#1]
大大好，看到了你们的论文，跟过来找到了Github，看完代码有几个问题想要问一下

1. OCR部分，论文中有根据笔画的编辑距离来筛选，但代码中我没有找到这部分的实现，请问这部分放到代码里面了吗？

2. ASR部分，论文中有几种error的判断（DNTC）并筛选，这部分在代码中有体现吗？

谢谢

**Comment by Toddzhangwj** [comment]
您好，请问您最后有生成数据成功嘛。
